version: '3.8'

services:
  quiz_db:
    image: mysql:8.0
    container_name: quiz_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: minao_quiz
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - quiznet

  quiz_service:
    build: .
    container_name: quiz_service
    environment:
      - DATABASE_URL=mysql://root:rootpassword@quiz_db:3306/minao_quiz
    depends_on:
      - quiz_db
    ports:
      - "3001:3001"  # Aqu√≠ puedes cambiar el puerto si es necesario
    networks:
      - quiznet

networks:
  quiznet:
    driver: bridge
